import type { OperatorTag } from "@/entities/operator-tag";
import type { Segment, Setlist, TimelineEntry } from "@/entities/segment";
import type { Show } from "@/entities/show";
import type { Venue } from "@/entities/venue";
import type { ChartTag, SegmentEngagement } from "@/widgets/post-show-chart";

// ============================================================================
// Post-show data indexed by dashboard show ID
// ============================================================================

export interface PostShowData {
  show: Show;
  timeline: TimelineEntry[];
  engagement: SegmentEngagement[];
  tags: OperatorTag[];
  chartTags: ChartTag[];
}

// ---------------------------------------------------------------------------
// show-d2: Quebonafide — Północ/Południe, Teatr Wielki, Warszawa
// Dashboard: 18 segments, duration=9160s, delta=+160s, engagement=74
// ---------------------------------------------------------------------------

const VENUE_D2: Venue = {
  id: "venue-d4",
  name: "Teatr Wielki",
  type: "hall",
  capacity: 3000,
  city: "Warszawa",
};

// Segments built from loaded templates:
// tpl-1 (Quebonafide): Tatuaż, Candy, Bubbletea, Jesień, Szubiepp
// tpl-3 (Sobel — support): Impreza, Fiołkowe pole, Dwa serca, Wszystko OK, Chwile, Na zawsze
// + segmenty techniczne (intro, przerwy, outro) + encore
const SEGMENTS_D2: Segment[] = [
  {
    id: "d4-seg-1",
    name: "Intro (video)",
    position: 1,
    type: "intro",
    expected_energy: 0.3,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v1", variant_type: "full", duration_seconds: 120 }],
  },
  // — Sobel (support) —
  {
    id: "d4-seg-2",
    name: "Impreza",
    position: 2,
    type: "song",
    bpm: 90,
    genre: "pop",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v2a", variant_type: "full", duration_seconds: 210 },
      { id: "d4-v2b", variant_type: "short", duration_seconds: 165 },
    ],
  },
  {
    id: "d4-seg-3",
    name: "Fiołkowe pole",
    position: 3,
    type: "song",
    bpm: 110,
    genre: "pop",
    expected_energy: 0.8,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [
      { id: "d4-v3a", variant_type: "full", duration_seconds: 200 },
      { id: "d4-v3b", variant_type: "short", duration_seconds: 150 },
    ],
  },
  {
    id: "d4-seg-4",
    name: "Dwa serca",
    position: 4,
    type: "song",
    bpm: 100,
    genre: "pop",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v4", variant_type: "full", duration_seconds: 180 }],
  },
  {
    id: "d4-seg-5",
    name: "Wszystko OK",
    position: 5,
    type: "song",
    bpm: 85,
    genre: "pop",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v5a", variant_type: "full", duration_seconds: 240 },
      { id: "d4-v5b", variant_type: "short", duration_seconds: 180 },
    ],
  },
  {
    id: "d4-seg-6",
    name: "Chwile",
    position: 6,
    type: "song",
    bpm: 75,
    genre: "pop",
    expected_energy: 0.4,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v6a", variant_type: "full", duration_seconds: 240 },
      { id: "d4-v6b", variant_type: "short", duration_seconds: 180 },
    ],
  },
  {
    id: "d4-seg-7",
    name: "Na zawsze",
    position: 7,
    type: "song",
    bpm: 95,
    genre: "pop",
    expected_energy: 0.65,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v7", variant_type: "full", duration_seconds: 215 }],
  },
  {
    id: "d4-seg-8",
    name: "Przerwa (przebudowa sceny)",
    position: 8,
    type: "interlude",
    expected_energy: 0.3,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v8", variant_type: "full", duration_seconds: 195 }],
  },
  // — Quebonafide (headliner) —
  {
    id: "d4-seg-9",
    name: "Tatuaż",
    position: 9,
    type: "song",
    bpm: 90,
    genre: "hip-hop",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v9a", variant_type: "full", duration_seconds: 210 },
      { id: "d4-v9b", variant_type: "short", duration_seconds: 165 },
    ],
  },
  {
    id: "d4-seg-10",
    name: "Candy",
    position: 10,
    type: "song",
    bpm: 110,
    genre: "hip-hop",
    expected_energy: 0.8,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [
      { id: "d4-v10a", variant_type: "full", duration_seconds: 200 },
      { id: "d4-v10b", variant_type: "short", duration_seconds: 150 },
    ],
  },
  {
    id: "d4-seg-11",
    name: "Bubbletea",
    position: 11,
    type: "song",
    bpm: 100,
    genre: "hip-hop",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v11", variant_type: "full", duration_seconds: 190 }],
  },
  {
    id: "d4-seg-12",
    name: "Jesień",
    position: 12,
    type: "song",
    bpm: 75,
    genre: "hip-hop",
    expected_energy: 0.4,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v12a", variant_type: "full", duration_seconds: 225 },
      { id: "d4-v12b", variant_type: "short", duration_seconds: 170 },
    ],
  },
  {
    id: "d4-seg-13",
    name: "Szubiepp",
    position: 13,
    type: "song",
    bpm: 130,
    genre: "hip-hop",
    expected_energy: 0.95,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v13", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d4-seg-14",
    name: "Przerwa DJ",
    position: 14,
    type: "interlude",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v14", variant_type: "full", duration_seconds: 250 }],
  },
  // — Encore —
  {
    id: "d4-seg-15",
    name: "Candy (encore)",
    position: 15,
    type: "song",
    bpm: 110,
    genre: "hip-hop",
    expected_energy: 0.92,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v15", variant_type: "full", duration_seconds: 205 }],
  },
  {
    id: "d4-seg-16",
    name: "Szubiepp (encore)",
    position: 16,
    type: "song",
    bpm: 130,
    genre: "hip-hop",
    expected_energy: 0.95,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v16", variant_type: "full", duration_seconds: 195 }],
  },
  {
    id: "d4-seg-17",
    name: "Tatuaż (encore)",
    position: 17,
    type: "song",
    bpm: 90,
    genre: "hip-hop",
    expected_energy: 0.88,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v17", variant_type: "full", duration_seconds: 230 }],
  },
  {
    id: "d4-seg-18",
    name: "Outro",
    position: 18,
    type: "outro",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v18", variant_type: "full", duration_seconds: 90 }],
  },
];

const SETLIST_D2: Setlist = {
  id: "setlist-d4",
  name: "Quebonafide — Północ/Południe",
  segments: SEGMENTS_D2,
  total_planned_duration_seconds: 9000,
};

const SHOW_D2: Show = {
  id: "show-d2",
  name: "Quebonafide — Północ/Południe",
  status: "ended",
  scheduled_start: "2026-02-14T20:00:00+01:00",
  scheduled_end: "2026-02-14T22:30:00+01:00",
  curfew: "2026-02-14T23:00:00+01:00",
  actual_start: "2026-02-14T20:03:00+01:00",
  venue: VENUE_D2,
  setlist: SETLIST_D2,
};

// Timeline: 17 completed, seg-14 skipped (recovery — opóźnienie). Total actual ≈ 9160s
const TIMELINE_D2: TimelineEntry[] = [
  {
    id: "ps-entry-1",
    segment_id: "d4-seg-1",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:03:00+01:00",
    ended_at: "2026-02-14T20:05:05+01:00",
    planned_duration_seconds: 120,
    actual_duration_seconds: 125,
    delta_seconds: 5,
  },
  {
    id: "ps-entry-2",
    segment_id: "d4-seg-2",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:05:15+01:00",
    ended_at: "2026-02-14T20:09:00+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 225,
    delta_seconds: 15,
  },
  {
    id: "ps-entry-3",
    segment_id: "d4-seg-3",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:09:20+01:00",
    ended_at: "2026-02-14T20:12:55+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 215,
    delta_seconds: 15,
  },
  {
    id: "ps-entry-4",
    segment_id: "d4-seg-4",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:13:10+01:00",
    ended_at: "2026-02-14T20:16:10+01:00",
    planned_duration_seconds: 180,
    actual_duration_seconds: 180,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-5",
    segment_id: "d4-seg-5",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:16:30+01:00",
    ended_at: "2026-02-14T20:20:40+01:00",
    planned_duration_seconds: 240,
    actual_duration_seconds: 250,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-6",
    segment_id: "d4-seg-6",
    status: "completed",
    variant_used: "short",
    started_at: "2026-02-14T20:21:00+01:00",
    ended_at: "2026-02-14T20:24:05+01:00",
    planned_duration_seconds: 240,
    actual_duration_seconds: 185,
    delta_seconds: -55,
  },
  {
    id: "ps-entry-7",
    segment_id: "d4-seg-7",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:24:20+01:00",
    ended_at: "2026-02-14T20:27:55+01:00",
    planned_duration_seconds: 215,
    actual_duration_seconds: 215,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-8",
    segment_id: "d4-seg-8",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:28:10+01:00",
    ended_at: "2026-02-14T20:31:35+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 205,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-9",
    segment_id: "d4-seg-9",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:31:50+01:00",
    ended_at: "2026-02-14T20:34:50+01:00",
    planned_duration_seconds: 180,
    actual_duration_seconds: 180,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-10",
    segment_id: "d4-seg-10",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:35:10+01:00",
    ended_at: "2026-02-14T20:38:50+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 220,
    delta_seconds: 20,
  },
  {
    id: "ps-entry-11",
    segment_id: "d4-seg-11",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:39:05+01:00",
    ended_at: "2026-02-14T20:42:20+01:00",
    planned_duration_seconds: 190,
    actual_duration_seconds: 195,
    delta_seconds: 5,
  },
  {
    id: "ps-entry-12",
    segment_id: "d4-seg-12",
    status: "completed",
    variant_used: "short",
    started_at: "2026-02-14T20:42:40+01:00",
    ended_at: "2026-02-14T20:45:40+01:00",
    planned_duration_seconds: 225,
    actual_duration_seconds: 180,
    delta_seconds: -45,
  },
  {
    id: "ps-entry-13",
    segment_id: "d4-seg-13",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:46:00+01:00",
    ended_at: "2026-02-14T20:49:30+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 210,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-14",
    segment_id: "d4-seg-14",
    status: "skipped",
    planned_duration_seconds: 250,
    actual_duration_seconds: 0,
    delta_seconds: -250,
  },
  {
    id: "ps-entry-15",
    segment_id: "d4-seg-15",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:49:50+01:00",
    ended_at: "2026-02-14T20:53:30+01:00",
    planned_duration_seconds: 205,
    actual_duration_seconds: 220,
    delta_seconds: 15,
  },
  {
    id: "ps-entry-16",
    segment_id: "d4-seg-16",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:53:45+01:00",
    ended_at: "2026-02-14T20:57:10+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 205,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-17",
    segment_id: "d4-seg-17",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T20:57:30+01:00",
    ended_at: "2026-02-14T21:01:30+01:00",
    planned_duration_seconds: 230,
    actual_duration_seconds: 240,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-18",
    segment_id: "d4-seg-18",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-14T21:01:45+01:00",
    ended_at: "2026-02-14T21:03:25+01:00",
    planned_duration_seconds: 90,
    actual_duration_seconds: 100,
    delta_seconds: 10,
  },
];

// Engagement per segment (avg across segments ≈ 74)
const ENGAGEMENT_D2: SegmentEngagement[] = [
  { segment_id: "d4-seg-1", segment_name: "Intro (video)", avg_score: 55, peak_score: 62 },
  { segment_id: "d4-seg-2", segment_name: "Impreza", avg_score: 68, peak_score: 79 },
  { segment_id: "d4-seg-3", segment_name: "Fiołkowe pole", avg_score: 82, peak_score: 91 },
  { segment_id: "d4-seg-4", segment_name: "Dwa serca", avg_score: 73, peak_score: 84 },
  { segment_id: "d4-seg-5", segment_name: "Wszystko OK", avg_score: 61, peak_score: 70 },
  { segment_id: "d4-seg-6", segment_name: "Chwile", avg_score: 58, peak_score: 66 },
  { segment_id: "d4-seg-7", segment_name: "Na zawsze", avg_score: 72, peak_score: 81 },
  {
    segment_id: "d4-seg-8",
    segment_name: "Przerwa (przebudowa sceny)",
    avg_score: 42,
    peak_score: 50,
  },
  { segment_id: "d4-seg-9", segment_name: "Tatuaż", avg_score: 77, peak_score: 86 },
  { segment_id: "d4-seg-10", segment_name: "Candy", avg_score: 85, peak_score: 93 },
  { segment_id: "d4-seg-11", segment_name: "Bubbletea", avg_score: 76, peak_score: 84 },
  { segment_id: "d4-seg-12", segment_name: "Jesień", avg_score: 63, peak_score: 72 },
  { segment_id: "d4-seg-13", segment_name: "Szubiepp", avg_score: 94, peak_score: 99 },
  { segment_id: "d4-seg-14", segment_name: "Przerwa DJ", avg_score: 52, peak_score: 60 },
  { segment_id: "d4-seg-15", segment_name: "Candy (encore)", avg_score: 88, peak_score: 96 },
  { segment_id: "d4-seg-16", segment_name: "Szubiepp (encore)", avg_score: 91, peak_score: 98 },
  { segment_id: "d4-seg-17", segment_name: "Tatuaż (encore)", avg_score: 83, peak_score: 92 },
  { segment_id: "d4-seg-18", segment_name: "Outro", avg_score: 70, peak_score: 78 },
];

// Tagi operatora — tylko te, które faktycznie kliknięto z QuickTags podczas live
const TAGS_D2: OperatorTag[] = [
  { id: "d4-tag-1", tag: "Peak ⚡", timestamp: "2026-02-14T20:30:00+01:00" },
  { id: "d4-tag-2", tag: "Low energy ↓", timestamp: "2026-02-14T20:22:00+01:00" },
];

const CHART_TAGS_D2: ChartTag[] = [
  { segment_id: "d4-seg-8", tag: "Peak ⚡" },
  { segment_id: "d4-seg-6", tag: "Low energy ↓" },
];

// ---------------------------------------------------------------------------
// show-d3: Mata — Hala Tour, Ergo Arena, Gdańsk
// Dashboard: 24 segments, duration=10770s, delta=-30s, engagement=81
// ---------------------------------------------------------------------------

const VENUE_D3: Venue = {
  id: "venue-d5",
  name: "Ergo Arena",
  type: "hall",
  capacity: 11000,
  city: "Gdańsk",
};

const SEGMENTS_D3: Segment[] = [
  {
    id: "d5-seg-1",
    name: "Intro (Patointeligencja)",
    position: 1,
    type: "intro",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v1", variant_type: "full", duration_seconds: 90 }],
  },
  {
    id: "d5-seg-2",
    name: "Patointeligencja",
    position: 2,
    type: "song",
    bpm: 130,
    genre: "hip-hop",
    expected_energy: 0.9,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v2", variant_type: "full", duration_seconds: 210 }],
  },
  {
    id: "d5-seg-3",
    name: "Kiss cam",
    position: 3,
    type: "song",
    bpm: 100,
    genre: "pop",
    expected_energy: 0.75,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [
      { id: "d5-v3a", variant_type: "full", duration_seconds: 200 },
      { id: "d5-v3b", variant_type: "short", duration_seconds: 155 },
    ],
  },
  {
    id: "d5-seg-4",
    name: "Hałas",
    position: 4,
    type: "song",
    bpm: 140,
    genre: "hip-hop",
    expected_energy: 0.85,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v4", variant_type: "full", duration_seconds: 185 }],
  },
  {
    id: "d5-seg-5",
    name: "Mama I'm a Criminal",
    position: 5,
    type: "song",
    bpm: 95,
    genre: "hip-hop",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v5a", variant_type: "full", duration_seconds: 220 },
      { id: "d5-v5b", variant_type: "short", duration_seconds: 170 },
    ],
  },
  {
    id: "d5-seg-6",
    name: "Nowy Jork",
    position: 6,
    type: "song",
    bpm: 108,
    genre: "hip-hop",
    expected_energy: 0.8,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v6", variant_type: "full", duration_seconds: 195 }],
  },
  {
    id: "d5-seg-7",
    name: "100 dni do matury",
    position: 7,
    type: "song",
    bpm: 118,
    genre: "hip-hop",
    expected_energy: 0.88,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v7", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d5-seg-8",
    name: "Interlude — DJ set",
    position: 8,
    type: "interlude",
    expected_energy: 0.55,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v8a", variant_type: "full", duration_seconds: 180 },
      { id: "d5-v8b", variant_type: "short", duration_seconds: 120 },
    ],
  },
  {
    id: "d5-seg-9",
    name: "Lato w Grecji",
    position: 9,
    type: "song",
    bpm: 105,
    genre: "pop",
    expected_energy: 0.72,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v9a", variant_type: "full", duration_seconds: 210 },
      { id: "d5-v9b", variant_type: "short", duration_seconds: 160 },
    ],
  },
  {
    id: "d5-seg-10",
    name: "Zdrówko",
    position: 10,
    type: "song",
    bpm: 92,
    genre: "hip-hop",
    expected_energy: 0.65,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v10a", variant_type: "full", duration_seconds: 230 },
      { id: "d5-v10b", variant_type: "short", duration_seconds: 175 },
    ],
  },
  {
    id: "d5-seg-11",
    name: "Papuga",
    position: 11,
    type: "song",
    bpm: 125,
    genre: "hip-hop",
    expected_energy: 0.82,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v11", variant_type: "full", duration_seconds: 190 }],
  },
  {
    id: "d5-seg-12",
    name: "Serce",
    position: 12,
    type: "song",
    bpm: 78,
    genre: "pop",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v12a", variant_type: "full", duration_seconds: 245 },
      { id: "d5-v12b", variant_type: "short", duration_seconds: 185 },
    ],
  },
  {
    id: "d5-seg-13",
    name: "SOS",
    position: 13,
    type: "song",
    bpm: 135,
    genre: "hip-hop",
    expected_energy: 0.92,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v13", variant_type: "full", duration_seconds: 195 }],
  },
  {
    id: "d5-seg-14",
    name: "Pierwszy lot",
    position: 14,
    type: "song",
    bpm: 88,
    genre: "hip-hop",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v14a", variant_type: "full", duration_seconds: 215 },
      { id: "d5-v14b", variant_type: "short", duration_seconds: 165 },
    ],
  },
  {
    id: "d5-seg-15",
    name: "6 zer",
    position: 15,
    type: "song",
    bpm: 110,
    genre: "hip-hop",
    expected_energy: 0.78,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v15", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d5-seg-16",
    name: "Przerwa techniczna",
    position: 16,
    type: "interlude",
    expected_energy: 0.4,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v16a", variant_type: "full", duration_seconds: 150 },
      { id: "d5-v16b", variant_type: "short", duration_seconds: 90 },
    ],
  },
  {
    id: "d5-seg-17",
    name: "Ostatni taniec",
    position: 17,
    type: "song",
    bpm: 82,
    genre: "pop",
    expected_energy: 0.55,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v17a", variant_type: "full", duration_seconds: 235 },
      { id: "d5-v17b", variant_type: "short", duration_seconds: 180 },
    ],
  },
  {
    id: "d5-seg-18",
    name: "Trend",
    position: 18,
    type: "song",
    bpm: 128,
    genre: "hip-hop",
    expected_energy: 0.87,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v18", variant_type: "full", duration_seconds: 190 }],
  },
  {
    id: "d5-seg-19",
    name: "Młody Matczak",
    position: 19,
    type: "song",
    bpm: 115,
    genre: "hip-hop",
    expected_energy: 0.8,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v19", variant_type: "full", duration_seconds: 205 }],
  },
  {
    id: "d5-seg-20",
    name: "Basen",
    position: 20,
    type: "song",
    bpm: 98,
    genre: "pop",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v20a", variant_type: "full", duration_seconds: 210 },
      { id: "d5-v20b", variant_type: "short", duration_seconds: 160 },
    ],
  },
  {
    id: "d5-seg-21",
    name: "Zostań tu",
    position: 21,
    type: "song",
    bpm: 85,
    genre: "pop",
    expected_energy: 0.58,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v21a", variant_type: "full", duration_seconds: 220 },
      { id: "d5-v21b", variant_type: "short", duration_seconds: 170 },
    ],
  },
  {
    id: "d5-seg-22",
    name: "Hala Tour Anthem",
    position: 22,
    type: "song",
    bpm: 145,
    genre: "hip-hop",
    expected_energy: 0.95,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v22", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d5-seg-23",
    name: "Encore — Patointeligencja (reprise)",
    position: 23,
    type: "song",
    bpm: 130,
    genre: "hip-hop",
    expected_energy: 0.93,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v23", variant_type: "full", duration_seconds: 240 }],
  },
  {
    id: "d5-seg-24",
    name: "Outro",
    position: 24,
    type: "outro",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v24", variant_type: "full", duration_seconds: 85 }],
  },
];

const SETLIST_D3: Setlist = {
  id: "setlist-d5",
  name: "Mata — Hala Tour",
  segments: SEGMENTS_D3,
  total_planned_duration_seconds: 10800,
};

const SHOW_D3: Show = {
  id: "show-d3",
  name: "Mata — Hala Tour",
  status: "ended",
  scheduled_start: "2026-02-10T20:00:00+01:00",
  scheduled_end: "2026-02-10T23:00:00+01:00",
  curfew: "2026-02-10T23:00:00+01:00",
  actual_start: "2026-02-10T20:01:00+01:00",
  venue: VENUE_D3,
  setlist: SETLIST_D3,
};

// Timeline: 24 completed, 0 skips, 2x short variant. Total actual ≈ 10770s
const TIMELINE_D3: TimelineEntry[] = [
  {
    id: "ps-entry-20",
    segment_id: "d5-seg-1",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:01:00+01:00",
    ended_at: "2026-02-10T20:02:30+01:00",
    planned_duration_seconds: 90,
    actual_duration_seconds: 90,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-21",
    segment_id: "d5-seg-2",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:02:45+01:00",
    ended_at: "2026-02-10T20:06:25+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 220,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-22",
    segment_id: "d5-seg-3",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:06:40+01:00",
    ended_at: "2026-02-10T20:10:00+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 200,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-23",
    segment_id: "d5-seg-4",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:10:15+01:00",
    ended_at: "2026-02-10T20:13:20+01:00",
    planned_duration_seconds: 185,
    actual_duration_seconds: 185,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-24",
    segment_id: "d5-seg-5",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:13:35+01:00",
    ended_at: "2026-02-10T20:17:15+01:00",
    planned_duration_seconds: 220,
    actual_duration_seconds: 220,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-25",
    segment_id: "d5-seg-6",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:17:30+01:00",
    ended_at: "2026-02-10T20:20:45+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 195,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-26",
    segment_id: "d5-seg-7",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:21:00+01:00",
    ended_at: "2026-02-10T20:24:30+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 210,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-27",
    segment_id: "d5-seg-8",
    status: "completed",
    variant_used: "short",
    started_at: "2026-02-10T20:24:45+01:00",
    ended_at: "2026-02-10T20:26:45+01:00",
    planned_duration_seconds: 180,
    actual_duration_seconds: 120,
    delta_seconds: -60,
  },
  {
    id: "ps-entry-28",
    segment_id: "d5-seg-9",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:27:00+01:00",
    ended_at: "2026-02-10T20:30:30+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 210,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-29",
    segment_id: "d5-seg-10",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:30:45+01:00",
    ended_at: "2026-02-10T20:34:35+01:00",
    planned_duration_seconds: 230,
    actual_duration_seconds: 230,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-30",
    segment_id: "d5-seg-11",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:34:50+01:00",
    ended_at: "2026-02-10T20:38:00+01:00",
    planned_duration_seconds: 190,
    actual_duration_seconds: 190,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-31",
    segment_id: "d5-seg-12",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:38:15+01:00",
    ended_at: "2026-02-10T20:42:20+01:00",
    planned_duration_seconds: 245,
    actual_duration_seconds: 245,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-32",
    segment_id: "d5-seg-13",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:42:35+01:00",
    ended_at: "2026-02-10T20:45:55+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 200,
    delta_seconds: 5,
  },
  {
    id: "ps-entry-33",
    segment_id: "d5-seg-14",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:46:10+01:00",
    ended_at: "2026-02-10T20:49:45+01:00",
    planned_duration_seconds: 215,
    actual_duration_seconds: 215,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-34",
    segment_id: "d5-seg-15",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:50:00+01:00",
    ended_at: "2026-02-10T20:53:20+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 200,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-35",
    segment_id: "d5-seg-16",
    status: "completed",
    variant_used: "short",
    started_at: "2026-02-10T20:53:35+01:00",
    ended_at: "2026-02-10T20:55:05+01:00",
    planned_duration_seconds: 150,
    actual_duration_seconds: 90,
    delta_seconds: -60,
  },
  {
    id: "ps-entry-36",
    segment_id: "d5-seg-17",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:55:20+01:00",
    ended_at: "2026-02-10T20:59:15+01:00",
    planned_duration_seconds: 235,
    actual_duration_seconds: 235,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-37",
    segment_id: "d5-seg-18",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T20:59:30+01:00",
    ended_at: "2026-02-10T21:02:50+01:00",
    planned_duration_seconds: 190,
    actual_duration_seconds: 200,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-38",
    segment_id: "d5-seg-19",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T21:03:05+01:00",
    ended_at: "2026-02-10T21:06:30+01:00",
    planned_duration_seconds: 205,
    actual_duration_seconds: 205,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-39",
    segment_id: "d5-seg-20",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T21:06:45+01:00",
    ended_at: "2026-02-10T21:10:15+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 210,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-40",
    segment_id: "d5-seg-21",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T21:10:30+01:00",
    ended_at: "2026-02-10T21:14:10+01:00",
    planned_duration_seconds: 220,
    actual_duration_seconds: 220,
    delta_seconds: 0,
  },
  {
    id: "ps-entry-41",
    segment_id: "d5-seg-22",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T21:14:25+01:00",
    ended_at: "2026-02-10T21:17:55+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 210,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-42",
    segment_id: "d5-seg-23",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T21:18:10+01:00",
    ended_at: "2026-02-10T21:22:20+01:00",
    planned_duration_seconds: 240,
    actual_duration_seconds: 250,
    delta_seconds: 10,
  },
  {
    id: "ps-entry-43",
    segment_id: "d5-seg-24",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-10T21:22:35+01:00",
    ended_at: "2026-02-10T21:24:00+01:00",
    planned_duration_seconds: 85,
    actual_duration_seconds: 85,
    delta_seconds: 0,
  },
];

// Engagement per segment (avg across segments ≈ 81)
const ENGAGEMENT_D3: SegmentEngagement[] = [
  {
    segment_id: "d5-seg-1",
    segment_name: "Intro (Patointeligencja)",
    avg_score: 72,
    peak_score: 80,
  },
  { segment_id: "d5-seg-2", segment_name: "Patointeligencja", avg_score: 95, peak_score: 99 },
  { segment_id: "d5-seg-3", segment_name: "Kiss cam", avg_score: 78, peak_score: 87 },
  { segment_id: "d5-seg-4", segment_name: "Hałas", avg_score: 88, peak_score: 95 },
  { segment_id: "d5-seg-5", segment_name: "Mama I'm a Criminal", avg_score: 75, peak_score: 84 },
  { segment_id: "d5-seg-6", segment_name: "Nowy Jork", avg_score: 82, peak_score: 90 },
  { segment_id: "d5-seg-7", segment_name: "100 dni do matury", avg_score: 90, peak_score: 97 },
  { segment_id: "d5-seg-8", segment_name: "Interlude — DJ set", avg_score: 58, peak_score: 65 },
  { segment_id: "d5-seg-9", segment_name: "Lato w Grecji", avg_score: 76, peak_score: 85 },
  { segment_id: "d5-seg-10", segment_name: "Zdrówko", avg_score: 70, peak_score: 79 },
  { segment_id: "d5-seg-11", segment_name: "Papuga", avg_score: 84, peak_score: 92 },
  { segment_id: "d5-seg-12", segment_name: "Serce", avg_score: 62, peak_score: 71 },
  { segment_id: "d5-seg-13", segment_name: "SOS", avg_score: 92, peak_score: 98 },
  { segment_id: "d5-seg-14", segment_name: "Pierwszy lot", avg_score: 68, peak_score: 77 },
  { segment_id: "d5-seg-15", segment_name: "6 zer", avg_score: 80, peak_score: 88 },
  { segment_id: "d5-seg-16", segment_name: "Przerwa techniczna", avg_score: 45, peak_score: 52 },
  { segment_id: "d5-seg-17", segment_name: "Ostatni taniec", avg_score: 65, peak_score: 74 },
  { segment_id: "d5-seg-18", segment_name: "Trend", avg_score: 87, peak_score: 94 },
  { segment_id: "d5-seg-19", segment_name: "Młody Matczak", avg_score: 83, peak_score: 91 },
  { segment_id: "d5-seg-20", segment_name: "Basen", avg_score: 74, peak_score: 82 },
  { segment_id: "d5-seg-21", segment_name: "Zostań tu", avg_score: 67, peak_score: 76 },
  { segment_id: "d5-seg-22", segment_name: "Hala Tour Anthem", avg_score: 96, peak_score: 100 },
  {
    segment_id: "d5-seg-23",
    segment_name: "Encore — Patointeligencja",
    avg_score: 94,
    peak_score: 99,
  },
  { segment_id: "d5-seg-24", segment_name: "Outro", avg_score: 73, peak_score: 81 },
];

// Tagi operatora — tylko te z QuickTags
const TAGS_D3: OperatorTag[] = [
  { id: "d5-tag-1", tag: "Peak ⚡", timestamp: "2026-02-10T20:04:00+01:00" },
  { id: "d5-tag-2", tag: "Great! ★", timestamp: "2026-02-10T21:16:00+01:00" },
];

const CHART_TAGS_D3: ChartTag[] = [
  { segment_id: "d5-seg-2", tag: "Peak ⚡" },
  { segment_id: "d5-seg-22", tag: "Great! ★" },
];

// ---------------------------------------------------------------------------
// show-d4: Dawid Podsiadło — Epicentrum Tour, Tauron Arena, Kraków
// Dashboard: 20 segments, duration=8640s, delta=-360s, engagement=89
// ---------------------------------------------------------------------------

const VENUE_D4: Venue = {
  id: "venue-d4",
  name: "Tauron Arena",
  type: "hall",
  capacity: 15000,
  city: "Kraków",
};

const SEGMENTS_D4: Segment[] = [
  {
    id: "d4-seg-1",
    name: "Intro (Epicentrum)",
    position: 1,
    type: "intro",
    expected_energy: 0.4,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v1", variant_type: "full", duration_seconds: 100 }],
  },
  {
    id: "d4-seg-2",
    name: "Małomiasteczkowy",
    position: 2,
    type: "song",
    bpm: 120,
    genre: "pop",
    expected_energy: 0.9,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v2", variant_type: "full", duration_seconds: 240 }],
  },
  {
    id: "d4-seg-3",
    name: "Nie ma fal",
    position: 3,
    type: "song",
    bpm: 105,
    genre: "pop",
    expected_energy: 0.85,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [
      { id: "d4-v3a", variant_type: "full", duration_seconds: 230 },
      { id: "d4-v3b", variant_type: "short", duration_seconds: 175 },
    ],
  },
  {
    id: "d4-seg-4",
    name: "Trójkąty i kwadraty",
    position: 4,
    type: "song",
    bpm: 95,
    genre: "pop",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v4a", variant_type: "full", duration_seconds: 210 },
      { id: "d4-v4b", variant_type: "short", duration_seconds: 160 },
    ],
  },
  {
    id: "d4-seg-5",
    name: "Let You Down",
    position: 5,
    type: "song",
    bpm: 88,
    genre: "pop",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v5", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d4-seg-6",
    name: "Trofea",
    position: 6,
    type: "song",
    bpm: 115,
    genre: "pop",
    expected_energy: 0.8,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v6", variant_type: "full", duration_seconds: 195 }],
  },
  {
    id: "d4-seg-7",
    name: "Przerwa DJ",
    position: 7,
    type: "interlude",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v7a", variant_type: "full", duration_seconds: 180 },
      { id: "d4-v7b", variant_type: "short", duration_seconds: 120 },
    ],
  },
  {
    id: "d4-seg-8",
    name: "Gdzie jest Wally?",
    position: 8,
    type: "song",
    bpm: 128,
    genre: "pop",
    expected_energy: 0.88,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v8", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d4-seg-9",
    name: "Lekko",
    position: 9,
    type: "song",
    bpm: 100,
    genre: "pop",
    expected_energy: 0.75,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v9", variant_type: "full", duration_seconds: 210 }],
  },
  {
    id: "d4-seg-10",
    name: "Pastempomat",
    position: 10,
    type: "song",
    bpm: 92,
    genre: "pop",
    expected_energy: 0.65,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v10a", variant_type: "full", duration_seconds: 220 },
      { id: "d4-v10b", variant_type: "short", duration_seconds: 170 },
    ],
  },
  {
    id: "d4-seg-11",
    name: "Nieznajomy",
    position: 11,
    type: "song",
    bpm: 108,
    genre: "pop",
    expected_energy: 0.82,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v11", variant_type: "full", duration_seconds: 195 }],
  },
  {
    id: "d4-seg-12",
    name: "W dobrą stronę",
    position: 12,
    type: "song",
    bpm: 78,
    genre: "pop",
    expected_energy: 0.55,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v12a", variant_type: "full", duration_seconds: 230 },
      { id: "d4-v12b", variant_type: "short", duration_seconds: 175 },
    ],
  },
  {
    id: "d4-seg-13",
    name: "Przerwa techniczna",
    position: 13,
    type: "interlude",
    expected_energy: 0.35,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v13", variant_type: "full", duration_seconds: 150 }],
  },
  {
    id: "d4-seg-14",
    name: "Początek",
    position: 14,
    type: "song",
    bpm: 85,
    genre: "pop",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d4-v14", variant_type: "full", duration_seconds: 215 }],
  },
  {
    id: "d4-seg-15",
    name: "Byłaś dla mnie wszystkim",
    position: 15,
    type: "song",
    bpm: 75,
    genre: "pop",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d4-v15a", variant_type: "full", duration_seconds: 240 },
      { id: "d4-v15b", variant_type: "short", duration_seconds: 185 },
    ],
  },
  {
    id: "d4-seg-16",
    name: "Studio",
    position: 16,
    type: "song",
    bpm: 118,
    genre: "pop",
    expected_energy: 0.85,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v16", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d4-seg-17",
    name: "Będzie dobrze",
    position: 17,
    type: "song",
    bpm: 110,
    genre: "pop",
    expected_energy: 0.88,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v17", variant_type: "full", duration_seconds: 205 }],
  },
  {
    id: "d4-seg-18",
    name: "Małomiasteczkowy (encore)",
    position: 18,
    type: "song",
    bpm: 120,
    genre: "pop",
    expected_energy: 0.95,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v18", variant_type: "full", duration_seconds: 250 }],
  },
  {
    id: "d4-seg-19",
    name: "Nie ma fal (encore)",
    position: 19,
    type: "song",
    bpm: 105,
    genre: "pop",
    expected_energy: 0.92,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v19", variant_type: "full", duration_seconds: 240 }],
  },
  {
    id: "d4-seg-20",
    name: "Outro",
    position: 20,
    type: "outro",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d4-v20", variant_type: "full", duration_seconds: 80 }],
  },
];

const SETLIST_D4: Setlist = {
  id: "setlist-d4",
  name: "Dawid Podsiadło — Epicentrum Tour",
  segments: SEGMENTS_D4,
  total_planned_duration_seconds: 9000,
};

const SHOW_D4: Show = {
  id: "show-d4",
  name: "Dawid Podsiadło — Epicentrum Tour",
  status: "ended",
  scheduled_start: "2026-02-01T20:00:00+01:00",
  scheduled_end: "2026-02-01T22:30:00+01:00",
  curfew: "2026-02-01T23:00:00+01:00",
  actual_start: "2026-02-01T20:02:00+01:00",
  venue: VENUE_D4,
  setlist: SETLIST_D4,
};

// Timeline: 20 completed, 0 skips, 1x short variant. Total actual ≈ 8640s
const TIMELINE_D4: TimelineEntry[] = [
  {
    id: "ps-d4-1",
    segment_id: "d4-seg-1",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:02:00+01:00",
    ended_at: "2026-02-01T20:03:40+01:00",
    planned_duration_seconds: 100,
    actual_duration_seconds: 100,
    delta_seconds: 0,
  },
  {
    id: "ps-d4-2",
    segment_id: "d4-seg-2",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:03:55+01:00",
    ended_at: "2026-02-01T20:07:55+01:00",
    planned_duration_seconds: 240,
    actual_duration_seconds: 240,
    delta_seconds: 0,
  },
  {
    id: "ps-d4-3",
    segment_id: "d4-seg-3",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:08:10+01:00",
    ended_at: "2026-02-01T20:12:00+01:00",
    planned_duration_seconds: 230,
    actual_duration_seconds: 230,
    delta_seconds: 0,
  },
  {
    id: "ps-d4-4",
    segment_id: "d4-seg-4",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:12:15+01:00",
    ended_at: "2026-02-01T20:15:25+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 190,
    delta_seconds: -20,
  },
  {
    id: "ps-d4-5",
    segment_id: "d4-seg-5",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:15:40+01:00",
    ended_at: "2026-02-01T20:18:50+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 190,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-6",
    segment_id: "d4-seg-6",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:19:05+01:00",
    ended_at: "2026-02-01T20:22:10+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 185,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-7",
    segment_id: "d4-seg-7",
    status: "completed",
    variant_used: "short",
    started_at: "2026-02-01T20:22:25+01:00",
    ended_at: "2026-02-01T20:24:25+01:00",
    planned_duration_seconds: 180,
    actual_duration_seconds: 120,
    delta_seconds: -60,
  },
  {
    id: "ps-d4-8",
    segment_id: "d4-seg-8",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:24:40+01:00",
    ended_at: "2026-02-01T20:28:00+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 200,
    delta_seconds: 0,
  },
  {
    id: "ps-d4-9",
    segment_id: "d4-seg-9",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:28:15+01:00",
    ended_at: "2026-02-01T20:31:45+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 210,
    delta_seconds: 0,
  },
  {
    id: "ps-d4-10",
    segment_id: "d4-seg-10",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:32:00+01:00",
    ended_at: "2026-02-01T20:35:30+01:00",
    planned_duration_seconds: 220,
    actual_duration_seconds: 210,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-11",
    segment_id: "d4-seg-11",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:35:45+01:00",
    ended_at: "2026-02-01T20:39:00+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 195,
    delta_seconds: 0,
  },
  {
    id: "ps-d4-12",
    segment_id: "d4-seg-12",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:39:15+01:00",
    ended_at: "2026-02-01T20:42:55+01:00",
    planned_duration_seconds: 230,
    actual_duration_seconds: 220,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-13",
    segment_id: "d4-seg-13",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:43:10+01:00",
    ended_at: "2026-02-01T20:45:30+01:00",
    planned_duration_seconds: 150,
    actual_duration_seconds: 140,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-14",
    segment_id: "d4-seg-14",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:45:45+01:00",
    ended_at: "2026-02-01T20:49:10+01:00",
    planned_duration_seconds: 215,
    actual_duration_seconds: 205,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-15",
    segment_id: "d4-seg-15",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:49:25+01:00",
    ended_at: "2026-02-01T20:53:15+01:00",
    planned_duration_seconds: 240,
    actual_duration_seconds: 230,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-16",
    segment_id: "d4-seg-16",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:53:30+01:00",
    ended_at: "2026-02-01T20:56:40+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 190,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-17",
    segment_id: "d4-seg-17",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T20:56:55+01:00",
    ended_at: "2026-02-01T21:00:10+01:00",
    planned_duration_seconds: 205,
    actual_duration_seconds: 195,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-18",
    segment_id: "d4-seg-18",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T21:00:25+01:00",
    ended_at: "2026-02-01T21:04:25+01:00",
    planned_duration_seconds: 250,
    actual_duration_seconds: 240,
    delta_seconds: -10,
  },
  {
    id: "ps-d4-19",
    segment_id: "d4-seg-19",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T21:04:40+01:00",
    ended_at: "2026-02-01T21:08:20+01:00",
    planned_duration_seconds: 240,
    actual_duration_seconds: 220,
    delta_seconds: -20,
  },
  {
    id: "ps-d4-20",
    segment_id: "d4-seg-20",
    status: "completed",
    variant_used: "full",
    started_at: "2026-02-01T21:08:35+01:00",
    ended_at: "2026-02-01T21:09:55+01:00",
    planned_duration_seconds: 80,
    actual_duration_seconds: 80,
    delta_seconds: 0,
  },
];

// Engagement per segment (avg across segments ≈ 89)
const ENGAGEMENT_D4: SegmentEngagement[] = [
  { segment_id: "d4-seg-1", segment_name: "Intro (Epicentrum)", avg_score: 70, peak_score: 78 },
  { segment_id: "d4-seg-2", segment_name: "Małomiasteczkowy", avg_score: 97, peak_score: 100 },
  { segment_id: "d4-seg-3", segment_name: "Nie ma fal", avg_score: 93, peak_score: 98 },
  { segment_id: "d4-seg-4", segment_name: "Trójkąty i kwadraty", avg_score: 85, peak_score: 92 },
  { segment_id: "d4-seg-5", segment_name: "Let You Down", avg_score: 78, peak_score: 86 },
  { segment_id: "d4-seg-6", segment_name: "Trofea", avg_score: 90, peak_score: 95 },
  { segment_id: "d4-seg-7", segment_name: "Przerwa DJ", avg_score: 55, peak_score: 63 },
  { segment_id: "d4-seg-8", segment_name: "Gdzie jest Wally?", avg_score: 94, peak_score: 99 },
  { segment_id: "d4-seg-9", segment_name: "Lekko", avg_score: 87, peak_score: 93 },
  { segment_id: "d4-seg-10", segment_name: "Pastempomat", avg_score: 82, peak_score: 89 },
  { segment_id: "d4-seg-11", segment_name: "Nieznajomy", avg_score: 91, peak_score: 96 },
  { segment_id: "d4-seg-12", segment_name: "W dobrą stronę", avg_score: 76, peak_score: 84 },
  { segment_id: "d4-seg-13", segment_name: "Przerwa techniczna", avg_score: 48, peak_score: 55 },
  { segment_id: "d4-seg-14", segment_name: "Początek", avg_score: 83, peak_score: 90 },
  {
    segment_id: "d4-seg-15",
    segment_name: "Byłaś dla mnie wszystkim",
    avg_score: 88,
    peak_score: 94,
  },
  { segment_id: "d4-seg-16", segment_name: "Studio", avg_score: 92, peak_score: 97 },
  { segment_id: "d4-seg-17", segment_name: "Będzie dobrze", avg_score: 95, peak_score: 99 },
  {
    segment_id: "d4-seg-18",
    segment_name: "Małomiasteczkowy (encore)",
    avg_score: 98,
    peak_score: 100,
  },
  { segment_id: "d4-seg-19", segment_name: "Nie ma fal (encore)", avg_score: 96, peak_score: 100 },
  { segment_id: "d4-seg-20", segment_name: "Outro", avg_score: 75, peak_score: 82 },
];

const TAGS_D4: OperatorTag[] = [
  { id: "d4-tag-1", tag: "Peak ⚡", timestamp: "2026-02-01T20:04:00+01:00" },
  { id: "d4-tag-2", tag: "Great! ★", timestamp: "2026-02-01T21:02:00+01:00" },
  { id: "d4-tag-3", tag: "Peak ⚡", timestamp: "2026-02-01T20:25:00+01:00" },
];

const CHART_TAGS_D4: ChartTag[] = [
  { segment_id: "d4-seg-2", tag: "Peak ⚡" },
  { segment_id: "d4-seg-8", tag: "Peak ⚡" },
  { segment_id: "d4-seg-18", tag: "Great! ★" },
];

// ---------------------------------------------------------------------------
// show-d5: Sanah — Uczta Tour, Hala Stulecia, Wrocław
// Dashboard: 16 segments, duration=8820s, delta=+320s, engagement=67
// ---------------------------------------------------------------------------

const VENUE_D5: Venue = {
  id: "venue-d5",
  name: "Hala Stulecia",
  type: "hall",
  capacity: 10000,
  city: "Wrocław",
};

const SEGMENTS_D5: Segment[] = [
  {
    id: "d5-seg-1",
    name: "Intro (Uczta)",
    position: 1,
    type: "intro",
    expected_energy: 0.35,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d5-v1", variant_type: "full", duration_seconds: 110 }],
  },
  {
    id: "d5-seg-2",
    name: "Szampan",
    position: 2,
    type: "song",
    bpm: 105,
    genre: "pop",
    expected_energy: 0.8,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v2", variant_type: "full", duration_seconds: 220 }],
  },
  {
    id: "d5-seg-3",
    name: "Ale jazz!",
    position: 3,
    type: "song",
    bpm: 115,
    genre: "pop",
    expected_energy: 0.75,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [
      { id: "d5-v3a", variant_type: "full", duration_seconds: 200 },
      { id: "d5-v3b", variant_type: "short", duration_seconds: 155 },
    ],
  },
  {
    id: "d5-seg-4",
    name: "Pora roku",
    position: 4,
    type: "song",
    bpm: 82,
    genre: "pop",
    expected_energy: 0.55,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v4a", variant_type: "full", duration_seconds: 235 },
      { id: "d5-v4b", variant_type: "short", duration_seconds: 180 },
    ],
  },
  {
    id: "d5-seg-5",
    name: "No sory",
    position: 5,
    type: "song",
    bpm: 100,
    genre: "pop",
    expected_energy: 0.7,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v5", variant_type: "full", duration_seconds: 190 }],
  },
  {
    id: "d5-seg-6",
    name: "Przerwa (przebudowa sceny)",
    position: 6,
    type: "interlude",
    expected_energy: 0.3,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d5-v6", variant_type: "full", duration_seconds: 180 }],
  },
  {
    id: "d5-seg-7",
    name: "Kolońska i szlugi",
    position: 7,
    type: "song",
    bpm: 95,
    genre: "pop",
    expected_energy: 0.65,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v7a", variant_type: "full", duration_seconds: 215 },
      { id: "d5-v7b", variant_type: "short", duration_seconds: 165 },
    ],
  },
  {
    id: "d5-seg-8",
    name: "Invisible dress",
    position: 8,
    type: "song",
    bpm: 120,
    genre: "pop",
    expected_energy: 0.78,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v8", variant_type: "full", duration_seconds: 195 }],
  },
  {
    id: "d5-seg-9",
    name: "Melodia",
    position: 9,
    type: "song",
    bpm: 88,
    genre: "pop",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v9a", variant_type: "full", duration_seconds: 225 },
      { id: "d5-v9b", variant_type: "short", duration_seconds: 170 },
    ],
  },
  {
    id: "d5-seg-10",
    name: "2:00",
    position: 10,
    type: "song",
    bpm: 108,
    genre: "pop",
    expected_energy: 0.72,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v10", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d5-seg-11",
    name: "Przerwa DJ",
    position: 11,
    type: "interlude",
    expected_energy: 0.45,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v11a", variant_type: "full", duration_seconds: 160 },
      { id: "d5-v11b", variant_type: "short", duration_seconds: 100 },
    ],
  },
  {
    id: "d5-seg-12",
    name: "Ja na imię niewierna mam",
    position: 12,
    type: "song",
    bpm: 92,
    genre: "pop",
    expected_energy: 0.58,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [{ id: "d5-v12", variant_type: "full", duration_seconds: 210 }],
  },
  {
    id: "d5-seg-13",
    name: "Gdzie pada deszcz",
    position: 13,
    type: "song",
    bpm: 78,
    genre: "pop",
    expected_energy: 0.5,
    is_locked: false,
    is_skippable: true,
    has_pyro: false,
    variants: [
      { id: "d5-v13a", variant_type: "full", duration_seconds: 230 },
      { id: "d5-v13b", variant_type: "short", duration_seconds: 175 },
    ],
  },
  {
    id: "d5-seg-14",
    name: "Szampan (encore)",
    position: 14,
    type: "song",
    bpm: 105,
    genre: "pop",
    expected_energy: 0.85,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v14", variant_type: "full", duration_seconds: 230 }],
  },
  {
    id: "d5-seg-15",
    name: "No sory (encore)",
    position: 15,
    type: "song",
    bpm: 100,
    genre: "pop",
    expected_energy: 0.82,
    is_locked: true,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v15", variant_type: "full", duration_seconds: 200 }],
  },
  {
    id: "d5-seg-16",
    name: "Outro",
    position: 16,
    type: "outro",
    expected_energy: 0.6,
    is_locked: false,
    is_skippable: false,
    has_pyro: false,
    variants: [{ id: "d5-v16", variant_type: "full", duration_seconds: 80 }],
  },
];

const SETLIST_D5: Setlist = {
  id: "setlist-d5",
  name: "Sanah — Uczta Tour",
  segments: SEGMENTS_D5,
  total_planned_duration_seconds: 8500,
};

const SHOW_D5: Show = {
  id: "show-d5",
  name: "Sanah — Uczta Tour",
  status: "ended",
  scheduled_start: "2026-01-25T19:00:00+01:00",
  scheduled_end: "2026-01-25T21:30:00+01:00",
  curfew: "2026-01-25T22:00:00+01:00",
  actual_start: "2026-01-25T19:05:00+01:00",
  venue: VENUE_D5,
  setlist: SETLIST_D5,
};

// Timeline: 15 completed, seg-13 skipped. Total actual ≈ 8820s
const TIMELINE_D5: TimelineEntry[] = [
  {
    id: "ps-d5-1",
    segment_id: "d5-seg-1",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:05:00+01:00",
    ended_at: "2026-01-25T19:07:00+01:00",
    planned_duration_seconds: 110,
    actual_duration_seconds: 120,
    delta_seconds: 10,
  },
  {
    id: "ps-d5-2",
    segment_id: "d5-seg-2",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:07:15+01:00",
    ended_at: "2026-01-25T19:11:15+01:00",
    planned_duration_seconds: 220,
    actual_duration_seconds: 240,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-3",
    segment_id: "d5-seg-3",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:11:30+01:00",
    ended_at: "2026-01-25T19:15:10+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 220,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-4",
    segment_id: "d5-seg-4",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:15:25+01:00",
    ended_at: "2026-01-25T19:19:30+01:00",
    planned_duration_seconds: 235,
    actual_duration_seconds: 245,
    delta_seconds: 10,
  },
  {
    id: "ps-d5-5",
    segment_id: "d5-seg-5",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:19:45+01:00",
    ended_at: "2026-01-25T19:23:15+01:00",
    planned_duration_seconds: 190,
    actual_duration_seconds: 210,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-6",
    segment_id: "d5-seg-6",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:23:30+01:00",
    ended_at: "2026-01-25T19:26:50+01:00",
    planned_duration_seconds: 180,
    actual_duration_seconds: 200,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-7",
    segment_id: "d5-seg-7",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:27:05+01:00",
    ended_at: "2026-01-25T19:30:55+01:00",
    planned_duration_seconds: 215,
    actual_duration_seconds: 230,
    delta_seconds: 15,
  },
  {
    id: "ps-d5-8",
    segment_id: "d5-seg-8",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:31:10+01:00",
    ended_at: "2026-01-25T19:34:45+01:00",
    planned_duration_seconds: 195,
    actual_duration_seconds: 215,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-9",
    segment_id: "d5-seg-9",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:35:00+01:00",
    ended_at: "2026-01-25T19:39:00+01:00",
    planned_duration_seconds: 225,
    actual_duration_seconds: 240,
    delta_seconds: 15,
  },
  {
    id: "ps-d5-10",
    segment_id: "d5-seg-10",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:39:15+01:00",
    ended_at: "2026-01-25T19:42:55+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 220,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-11",
    segment_id: "d5-seg-11",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:43:10+01:00",
    ended_at: "2026-01-25T19:46:10+01:00",
    planned_duration_seconds: 160,
    actual_duration_seconds: 180,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-12",
    segment_id: "d5-seg-12",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:46:25+01:00",
    ended_at: "2026-01-25T19:50:25+01:00",
    planned_duration_seconds: 210,
    actual_duration_seconds: 240,
    delta_seconds: 30,
  },
  {
    id: "ps-d5-13",
    segment_id: "d5-seg-13",
    status: "skipped",
    planned_duration_seconds: 230,
    actual_duration_seconds: 0,
    delta_seconds: -230,
  },
  {
    id: "ps-d5-14",
    segment_id: "d5-seg-14",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:50:40+01:00",
    ended_at: "2026-01-25T19:54:50+01:00",
    planned_duration_seconds: 230,
    actual_duration_seconds: 250,
    delta_seconds: 20,
  },
  {
    id: "ps-d5-15",
    segment_id: "d5-seg-15",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:55:05+01:00",
    ended_at: "2026-01-25T19:58:55+01:00",
    planned_duration_seconds: 200,
    actual_duration_seconds: 230,
    delta_seconds: 30,
  },
  {
    id: "ps-d5-16",
    segment_id: "d5-seg-16",
    status: "completed",
    variant_used: "full",
    started_at: "2026-01-25T19:59:10+01:00",
    ended_at: "2026-01-25T20:00:30+01:00",
    planned_duration_seconds: 80,
    actual_duration_seconds: 80,
    delta_seconds: 0,
  },
];

// Engagement per segment (avg across segments ≈ 67)
const ENGAGEMENT_D5: SegmentEngagement[] = [
  { segment_id: "d5-seg-1", segment_name: "Intro (Uczta)", avg_score: 48, peak_score: 56 },
  { segment_id: "d5-seg-2", segment_name: "Szampan", avg_score: 82, peak_score: 90 },
  { segment_id: "d5-seg-3", segment_name: "Ale jazz!", avg_score: 75, peak_score: 83 },
  { segment_id: "d5-seg-4", segment_name: "Pora roku", avg_score: 58, peak_score: 67 },
  { segment_id: "d5-seg-5", segment_name: "No sory", avg_score: 72, peak_score: 80 },
  {
    segment_id: "d5-seg-6",
    segment_name: "Przerwa (przebudowa sceny)",
    avg_score: 35,
    peak_score: 42,
  },
  { segment_id: "d5-seg-7", segment_name: "Kolońska i szlugi", avg_score: 63, peak_score: 72 },
  { segment_id: "d5-seg-8", segment_name: "Invisible dress", avg_score: 77, peak_score: 85 },
  { segment_id: "d5-seg-9", segment_name: "Melodia", avg_score: 55, peak_score: 64 },
  { segment_id: "d5-seg-10", segment_name: "2:00", avg_score: 70, peak_score: 78 },
  { segment_id: "d5-seg-11", segment_name: "Przerwa DJ", avg_score: 40, peak_score: 48 },
  {
    segment_id: "d5-seg-12",
    segment_name: "Ja na imię niewierna mam",
    avg_score: 60,
    peak_score: 69,
  },
  { segment_id: "d5-seg-13", segment_name: "Gdzie pada deszcz", avg_score: 52, peak_score: 61 },
  { segment_id: "d5-seg-14", segment_name: "Szampan (encore)", avg_score: 85, peak_score: 93 },
  { segment_id: "d5-seg-15", segment_name: "No sory (encore)", avg_score: 80, peak_score: 88 },
  { segment_id: "d5-seg-16", segment_name: "Outro", avg_score: 55, peak_score: 62 },
];

const TAGS_D5: OperatorTag[] = [
  { id: "d5-tag-1", tag: "Low energy ↓", timestamp: "2026-01-25T19:24:00+01:00" },
  { id: "d5-tag-2", tag: "Peak ⚡", timestamp: "2026-01-25T19:51:00+01:00" },
];

const CHART_TAGS_D5: ChartTag[] = [
  { segment_id: "d5-seg-6", tag: "Low energy ↓" },
  { segment_id: "d5-seg-14", tag: "Peak ⚡" },
];

// ============================================================================
// Exported map: dashboard show ID → full post-show data
// ============================================================================

export const POSTSHOW_DATA: Record<string, PostShowData> = {
  "show-d2": {
    show: SHOW_D2,
    timeline: TIMELINE_D2,
    engagement: ENGAGEMENT_D2,
    tags: TAGS_D2,
    chartTags: CHART_TAGS_D2,
  },
  "show-d3": {
    show: SHOW_D3,
    timeline: TIMELINE_D3,
    engagement: ENGAGEMENT_D3,
    tags: TAGS_D3,
    chartTags: CHART_TAGS_D3,
  },
  "show-d4": {
    show: SHOW_D4,
    timeline: TIMELINE_D4,
    engagement: ENGAGEMENT_D4,
    tags: TAGS_D4,
    chartTags: CHART_TAGS_D4,
  },
  "show-d5": {
    show: SHOW_D5,
    timeline: TIMELINE_D5,
    engagement: ENGAGEMENT_D5,
    tags: TAGS_D5,
    chartTags: CHART_TAGS_D5,
  },
};
